AlignParameters:
  Enabled: false
Documentation:
  Enabled: false
LineLength:
  Max: 100
Metrics/AbcSize:
  Max: 20
MethodLength:
  CountComments: false
  Max: 10
ClassLength:
  CountComments: false
  Max: 100
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
  TargetRubyVersion: 2.4
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/AlignHash:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/DotPosition:
  EnforcedStyle: leading
Style/FrozenStringLiteralComment:
  Enabled: false
